from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class HybridSearchInput(BaseModel):
    """Input parameters for retrieving recipes using hybrid search."""

    intent_query: str = Field(
        description="The detailed natural language query describing the desired recipe type, cuisine, or flavor profile."
    )
    user_id: str = Field(
        description="The UUID string of the authenticated user requesting the recipe candidates."
    )
    exclude_ids: Optional[List[str]] = Field(
        default_factory=list,
        description="A list of Recipe UUID strings that the system should exclude (e.g., recipes rated 'too hard').",
    )
    similarity_threshold: Optional[float] = Field(
        default=0.3,
        description="The minimum semantic similarity score (0.0 to 1.0) required to consider a recipe relevant. Default is 0.3.",
    )
    limit: Optional[int] = Field(
        default=10, description="The maximum number of recipe candidates to return."
    )


class FinalPlanOutput(BaseModel):
    """The final list of Recipe IDs selected for the weekly plan."""

    final_recipe_ids: List[str] = Field(
        description="The definitive list of 7 (or user.frequency) Recipe UUID strings selected for the user's weekly plan."
    )


class RecipeSelectionInput(BaseModel):
    """Input for finalizing recipe selection."""

    recipe_ids: List[str] = Field(
        description="List of recipe IDs (as strings) to include in the weekly meal plan."
    )


class IngredientItem(BaseModel):
    """A single ingredient with its name and measurement."""

    name: str = Field(
        description=(
            "Food item only, lowercase preferred (e.g. 'bell pepper', 'garlic', 'salt'). "
            "Do NOT put quantity, 'to taste', or prep (sliced/minced) in name."
        )
    )
    measure: str = Field(
        description=(
            "Quantity, unit, and optional prep (e.g. '2 cups', '1 lb', '2 cloves, minced'). "
            "Use exactly 'to taste' for salt/pepper when unspecified — never put 'to taste' in name."
        )
    )


class InstructionStep(BaseModel):
    """A single instruction step with step number and text."""

    step: int = Field(description="The step number (1, 2, 3, etc.)")
    text: str = Field(
        description="The instruction text. Should be clear, concise, and properly capitalized with punctuation."
    )


class NewRecipeSchema(BaseModel):
    """The structured format for a new recipe generated by the LLM."""

    name: str = Field(
        description=(
            "Short, natural dish name only (2–6 words). Examples: 'Fried Rice', "
            "'Vegetable Stir-Fry', 'Tomato Basil Pasta'. Do NOT include skill level, "
            "marketing words, or prefixes like Beginner's, Easy, Mastery, Ultimate, "
            "Perfect, or Homestyle — difficulty is stored separately."
        )
    )
    cuisine: str = Field(
        description="The primary cuisine category (e.g., Italian, Chinese)."
    )
    ingredients: List[IngredientItem] = Field(
        description="List of ingredients, each with 'name' and 'measure' fields."
    )
    instructions: List[InstructionStep] = Field(
        description="Step-by-step cooking instructions as a structured list. Each step should have a number and clear text."
    )
    difficulty: Literal["easy", "medium", "hard"] = Field(
        description="The estimated difficulty level (easy, medium, hard)."
    )
    dietary_tags: List[str] = Field(
        description=(
            "Applicable dietary tags. Examples: vegetarian, vegan, gluten-free, "
            "dairy-free, pescatarian, keto. Use ['omnivore'] if none apply."
        ),
        min_length=1,
    )
    allergens: List[str] = Field(
        description=(
            "Allergens present in the recipe (nuts, dairy, eggs, wheat, shellfish, etc.). "
            "Use [] only if truly none."
        ),
    )
    portion_size: str = Field(
        description="Serving size, e.g. '4 servings' or '2-3 servings'."
    )
    prep_time_minutes: int = Field(
        description="Active prep time in minutes (chopping, mixing).",
        ge=1,
    )
    cook_time_minutes: int = Field(
        description="Cook/bake time in minutes. Use 0 for no-cook dishes.",
        ge=0,
    )
    skill_level_validated: Literal["beginner", "medium", "advanced"] = Field(
        description=(
            "Skill level for techniques required: beginner, medium, or advanced. "
            "Should align with difficulty (easy→beginner, medium→medium, hard→advanced)."
        ),
    )
